---
- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/default.yml"

- name: Apply apt package task
  ansible.builtin.import_tasks: apt_package.yml
  when: ansible_pkg_mgr == 'apt'

- name: Apply yum package task
  ansible.builtin.import_tasks: yum_package.yml
  when: ansible_pkg_mgr == 'yum' or ansible_pkg_mgr == 'dnf'



# - name: Ensure Docker is started
#   when: not ansible_check_mode
#   ansible.builtin.service:
#     name: docker
#     state: started
#     enabled: true
#   become: true
#   tags:
#     - docker
#     - service