---
- hosts: all
  gather_facts: no
  become: true
  tasks:
  - name: Copy the key add to authorized_keys using Ansible module
    tags: runcd
    authorized_key:
      user: "{{authorized_user}}"
      key: "{{rsa_pub}}"
      state: present
  handlers:
  - name: restart ssh
    service:
      name=sshd
      state=restarted