---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos
    image: quay.io/centos/centos:stream8
provisioner:
  name: ansible
  log: true
provisioner:
  name: ansible
  log: true
verifier:
  name: ansible
