---
- name: Install CentOS packages
  package:
    name: "{{ centos_packages }}"
    state: present
  become: yes

- name: Install Docker compose
  shell: curl -SL https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-linux-{ansible_machine} -o /usr/local/bin/docker-compose
  