---
# Configure podman

# - name: set user.max_user_namespaces
#   sysctl:
#     name: user.max_user_namespaces
#     value: "{{ proc_max_user_namespaces }}"
#     sysctl_set: yes
#     state: present
#     reload: yes
#   become: yes

- name: Install CentOS packages
  package:
    name: "{{ centos_packages }}"
    state: present
  become: yes


- name: Modify runroot storage path
  ansible.builtin.lineinfile:
    path: /etc/containers/storage.conf
    regexp: '^runroot ='
    line: runroot = "/opt/storage/data"


- name: Modify graphroot storage path
  ansible.builtin.lineinfile:
    path: /etc/containers/storage.conf
    regexp: '^graphroot ='
    line: graphroot = "/opt/storage/images"

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: ./../handlers/docker
    dest: /usr/local/bin/docker
    mode: u=xrw,g=r,o=r

- name: Create nodocker file
  shell: touch /etc/containers/nodocker

- name: Install Docker compose
  shell:  |
    curl -SL https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-linux-{{ansible_machine}} -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose