---
# Install podman on RedHat

- name: Install RedHat packages
  package:
    name: "{{ redhat_packages }}"
    state: present
  become: yes

- name: Enable socket
  ansible.builtin.service:
    name: podman.socket
    state: started
    enabled: yes

- name: Modify runroot storage path
  ansible.builtin.lineinfile:
    path: /etc/containers/storage.conf
    regexp: '^runroot ='
    line: runroot = "/opt/storage/data"
