---
# Install podman on RedHat

- name: Install RedHat packages
  package:
    name: "{{ redhat_packages }}"
    state: present
  become: yes


- name: Modify runroot storage path
  ansible.builtin.lineinfile:
    path: /etc/containers/storage.conf
    regexp: '^runroot ='
    line: runroot = "/opt/storage/data"
